name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.16', '1.17', '1.18' ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Install cob
        run: curl -sfL https://raw.githubusercontent.com/knqyf263/cob/master/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Run test and build
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u github.com/shuLhan/go-bindata/...
          go install github.com/shuLhan/go-bindata/v4/cmd/go-bindata@master
          go-bindata -pkg bindata -o bindata/bindata.go etc/*
          go get ./...
          go build -ldflags "-X main.version=$(git describe --tags)" -o dbanon main.go
          go test -coverprofile=coverage.out -covermode=atomic -race -v ./...

      - name: Run Git Status
        run: git status

      - name: Run Benchmark
        run: cob

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3